<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OccupationSeeder extends Seeder
{
    public function run(): void
    {
        $occupations = [
            // RISK SCORE 1 - Low Risk (Office/Desk Jobs, Limited Danger)
            ['name' => 'Manager Keuangan', 'risk_score' => 1],
            ['name' => 'Content creator/youtuber/influencer', 'risk_score' => 1],
            ['name' => 'Staf bank/asuransi/hotel', 'risk_score' => 1],
            ['name' => 'Ibu rumah tangga/pelajar/mahasiswa/pensiunan', 'risk_score' => 1],
            ['name' => 'Sekretaris', 'risk_score' => 1],
            ['name' => 'Resepsionis', 'risk_score' => 1],
            ['name' => 'Petugas administrasi kantor pos', 'risk_score' => 1],
            ['name' => 'Fisioterapis', 'risk_score' => 1],
            ['name' => 'Pembaca berita', 'risk_score' => 1],
            ['name' => 'Model profesional', 'risk_score' => 1],
            ['name' => 'pendeta/pastor/rohaniwan/ustad/ustadzah (termasuk biarawan/biarawati)', 'risk_score' => 1],
            ['name' => 'Notaris', 'risk_score' => 1],
            ['name' => 'Manager bank, asuransi, hotel', 'risk_score' => 1],
            ['name' => 'Staf kedutaan', 'risk_score' => 1],
            ['name' => 'Penjahit', 'risk_score' => 1],
            ['name' => 'Staff admin pelabuhan', 'risk_score' => 1],
            ['name' => 'pramuniaga/customer service', 'risk_score' => 1],
            ['name' => 'Kameramen (film/televisi) & fotografer', 'risk_score' => 1],
            ['name' => 'Penyanyi & musisi', 'risk_score' => 1],
            ['name' => 'Pengasuh anak', 'risk_score' => 1],
            ['name' => 'Staf administrasi', 'risk_score' => 1],
            ['name' => 'Duta besar/atase kedutaan/diplomat', 'risk_score' => 1],
            ['name' => 'aktor/aktris/selebrity', 'risk_score' => 1],
            ['name' => 'Akuntan publik/konsultan pajak', 'risk_score' => 1],
            ['name' => 'Manager perusahaan', 'risk_score' => 1],
            ['name' => 'Direktur perusahaan', 'risk_score' => 1],
            ['name' => 'Konsultan pajak', 'risk_score' => 1],
            ['name' => 'Kurator', 'risk_score' => 1],
            ['name' => 'Pejabat pemerintah penyedia jasa keuangan', 'risk_score' => 1],
            ['name' => 'Pejabat, pegawai, petugas di bidang penerimaan negara', 'risk_score' => 1],
            ['name' => 'Pejabat, pegawai, petugas di bidang penyaluran barang', 'risk_score' => 1],
            ['name' => 'Pejabat, pegawai, petugas di bidang pengadaan', 'risk_score' => 1],
            ['name' => 'Pejabat, pegawai, petugas di bidang perizinan', 'risk_score' => 1],
            ['name' => 'Pejabat, pegawai, petugas di bidang pelayanan publik', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara pejabat pembuat regulasi', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara kepala unit pelayanan masyarakat', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara pejabat perizinan', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara auditor', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara pemeriksa pajak', 'risk_score' => 1],
            ['name' => 'Pejabat aparatur negara pemeriksa bea dan cukai', 'risk_score' => 1],
            ['name' => 'Kepala kantor kementerian keuangan', 'risk_score' => 1],
            ['name' => 'Pejabat Aparatur Negara Eselon II pada Instansi Pemerintahan/Lembaga Negara', 'risk_score' => 1],
            ['name' => 'Pimpinan komisi', 'risk_score' => 1],
            ['name' => 'Bendahara proyek pemerintah', 'risk_score' => 1],
            ['name' => 'Pimpinan proyek pemerintah', 'risk_score' => 1],
            ['name' => 'Panitera pengadilan', 'risk_score' => 1],
            ['name' => 'Pejabat Eselon I pada Lingkungan Sipil', 'risk_score' => 1],
            ['name' => 'Pimpinan PTN (Perguruan Tinggi Negeri)', 'risk_score' => 1],
            ['name' => 'Pejabat struktural pada BUMN dan BUMD', 'risk_score' => 1],
            ['name' => 'Komisaris pada BUMN dan BUMD', 'risk_score' => 1],
            ['name' => 'Direksi pada BUMN dan BUMD', 'risk_score' => 1],
            ['name' => 'Pimpinan Instansi Pemerintah Setara Eselon I', 'risk_score' => 1],
            ['name' => 'Wakil Walikota', 'risk_score' => 1],
            ['name' => 'Walikota', 'risk_score' => 1],
            ['name' => 'Wakil Bupati', 'risk_score' => 1],
            ['name' => 'Bupati', 'risk_score' => 1],
            ['name' => 'Wakil Gubernur', 'risk_score' => 1],
            ['name' => 'Gubernur', 'risk_score' => 1],
            ['name' => 'Pimpinan KPP (Komisi Pemberantasan Korupsi)', 'risk_score' => 1],
            ['name' => 'Anggota Dewan Komimsioner Otoritas Jasa Keuangan', 'risk_score' => 1],
            ['name' => 'Anggota Dewan Gubernur Bank Indonesia', 'risk_score' => 1],
            ['name' => 'Anggota BPK (Badan Pemeriksa Keuangan)', 'risk_score' => 1],
            ['name' => 'Anggota Dewan Pertimbangan Presiden', 'risk_score' => 1],
            ['name' => 'Komisi Yudisial', 'risk_score' => 1],
            ['name' => 'Hakim Konstitusi', 'risk_score' => 1],
            ['name' => 'Hakim Agung', 'risk_score' => 1],
            ['name' => 'Jabatan Setingkat Menteri', 'risk_score' => 1],
            ['name' => 'Wakil Menteri', 'risk_score' => 1],
            ['name' => 'Menteri', 'risk_score' => 1],
            ['name' => 'Wakil Presiden', 'risk_score' => 1],
            ['name' => 'Presiden', 'risk_score' => 1],
            ['name' => 'Advokat', 'risk_score' => 1],
            ['name' => 'Pengacara', 'risk_score' => 1],
            ['name' => 'Jaksa', 'risk_score' => 1],
            ['name' => 'Hakim', 'risk_score' => 1],
            ['name' => 'Balita/Belum bekerja', 'risk_score' => 1],
            ['name' => 'Pemilik usaha/pengusaha', 'risk_score' => 1],
            ['name' => 'PNS (Pegawai Negeri Sipil)', 'risk_score' => 1],
            ['name' => 'Pejabat negara', 'risk_score' => 1],
            ['name' => 'Dosen, guru', 'risk_score' => 1],
            ['name' => 'Pegawai toko', 'risk_score' => 1],
            ['name' => 'Akuntan/konsultan keuangan', 'risk_score' => 1],
            ['name' => 'Peramal cuaca', 'risk_score' => 1],
            ['name' => 'Pekerja sosial kantor', 'risk_score' => 1],
            ['name' => 'Pembuat atau tukang sepatu', 'risk_score' => 1],
            ['name' => 'Penulis naskah (film/televisi)', 'risk_score' => 1],
            ['name' => 'Produser (film/televisi)', 'risk_score' => 1],
            ['name' => 'Petugas pompa bensin', 'risk_score' => 1],
            ['name' => 'Petugas pemasang kabel listrik', 'risk_score' => 1],
            ['name' => 'Sutradara (film/televisi)', 'risk_score' => 1],
            ['name' => 'Perancang (busana/interior)', 'risk_score' => 1],
            ['name' => 'Kondektur (transportasi bus)', 'risk_score' => 1],
            ['name' => 'Tukang sepatu dan pembuat sepatu', 'risk_score' => 1],
            ['name' => 'Kasir', 'risk_score' => 1],
            ['name' => 'Penata rambut, penata rias, petugas perawatan kuku', 'risk_score' => 1],
            ['name' => 'Pembuat roti, pengurus adonan, pengemasan', 'risk_score' => 1],
            ['name' => 'Arsitek', 'risk_score' => 1],
            ['name' => 'Pemijat/tukang pijat', 'risk_score' => 1],
            ['name' => 'Penari (tradisional/modern/pertunjukan)', 'risk_score' => 1],

            // RISK SCORE 2 - Medium Risk (Some Danger, Physical Work, Patient Contact)
            ['name' => 'Tenaga pemasar/marketing/agen', 'risk_score' => 2],
            ['name' => 'Politisi/Anggota Partai/DPR/DPRD/DPD', 'risk_score' => 2],
            ['name' => 'Pendidikan militer/kepolisian (AKPOL/AKMIL)', 'risk_score' => 2],
            ['name' => 'Dokter', 'risk_score' => 2],
            ['name' => 'Bidan', 'risk_score' => 2],
            ['name' => 'Montir', 'risk_score' => 2],
            ['name' => 'Operator mesin pabrik', 'risk_score' => 2],
            ['name' => 'Wasit olahraga/hakim garis', 'risk_score' => 2],
            ['name' => 'Wartawan/reporter', 'risk_score' => 2],
            ['name' => 'Detektif/investigator', 'risk_score' => 2],
            ['name' => 'Instruktur senam/aerobik', 'risk_score' => 2],
            ['name' => 'PNS', 'risk_score' => 2],
            ['name' => 'Ahli geologi', 'risk_score' => 2],
            ['name' => 'Mandor bangunan', 'risk_score' => 2],
            ['name' => 'Nelayan', 'risk_score' => 2],
            ['name' => 'Teknisi listrik', 'risk_score' => 2],
            ['name' => 'Sopir kendaraan berukuran sedang (minibus, truk engkel dan box)', 'risk_score' => 2],
            ['name' => 'Sopir kendaraan berukuran besar (bus antar kota, dump truck, truk kontainer)', 'risk_score' => 2],
            ['name' => 'Sopir kendaraan berukuran kecil, mobil pribadi, taksi, angkutan kota', 'risk_score' => 2],
            ['name' => 'Pembantu rumah tangga', 'risk_score' => 2],
            ['name' => 'Pengantar barang/kurir', 'risk_score' => 2],
            ['name' => 'Kontraktor gedung/perumahan', 'risk_score' => 2],
            ['name' => 'Petugas kebersihan', 'risk_score' => 2],
            ['name' => 'Koki profesional', 'risk_score' => 2],
            ['name' => 'Pemilik usaha (angkutan/transportasi)', 'risk_score' => 2],
            ['name' => 'Tukang kayu', 'risk_score' => 2],
            ['name' => 'Petugas keamanan/satpam', 'risk_score' => 2],
            ['name' => 'Tukang bangunan', 'risk_score' => 2],
            ['name' => 'Pandai besi/pembuat peralatan dari bahan besi atau logam', 'risk_score' => 2],
            ['name' => 'Pekerja hotel (hoteliers)', 'risk_score' => 2],
            ['name' => 'Atlit profesional olahraga permainan (voli, tenis, basket, dll)', 'risk_score' => 2],
            ['name' => 'Pekerja/pelayan restoran, termasuk bartender/barista', 'risk_score' => 2],
            ['name' => 'Petani (buruh tani)', 'risk_score' => 2],
            ['name' => 'Pemilik usaha (pertanian/perkebunan/peternakan)', 'risk_score' => 2],
            ['name' => 'Polisi staff pelayanan', 'risk_score' => 2],
            ['name' => 'Pejabat pada sektor MIGAS (Minyak dan Gas) dan MINERBA (Mineral dan Batu Bara)', 'risk_score' => 2],
            ['name' => 'Penyidik', 'risk_score' => 2],
            ['name' => 'Tukang gali sumur', 'risk_score' => 2],
            ['name' => 'Tukang las', 'risk_score' => 2],
            ['name' => 'Vulkanologis', 'risk_score' => 2],
            ['name' => 'Pekerja sosial lapangan', 'risk_score' => 2],
            ['name' => 'Petugas pemeliharaan kereta api', 'risk_score' => 2],
            ['name' => 'Polisi lalu lintas', 'risk_score' => 2],
            ['name' => 'Petugas narkotika', 'risk_score' => 2],
            ['name' => 'Petugas penyelamat di pantai', 'risk_score' => 2],
            ['name' => 'Petugas penyelamat di kolam renang', 'risk_score' => 2],
            ['name' => 'Tukang kebun, pekerja landscape', 'risk_score' => 2],
            ['name' => 'Petugas sampah', 'risk_score' => 2],
            ['name' => 'Pekerja hutan', 'risk_score' => 2],
            ['name' => 'Buruh pabrik', 'risk_score' => 2],
            ['name' => 'Operator lift', 'risk_score' => 2],
            ['name' => 'Detektif (detektif untuk kasus kriminal/investigasi personal)', 'risk_score' => 2],
            ['name' => 'Awak kabin penerbangan komersial', 'risk_score' => 2],
            ['name' => 'Tukang daging (rumah potong)', 'risk_score' => 2],
            ['name' => 'Operator bulldozer', 'risk_score' => 2],
            ['name' => 'Petugas pengurus bagasi, muatan, kuli', 'risk_score' => 2],
            ['name' => 'Pekerja pengaspal jalan', 'risk_score' => 2],
            ['name' => 'Pelatih binatang, sirkus, hewan liar', 'risk_score' => 2],
            ['name' => 'Petugas/staf rumah sakit', 'risk_score' => 2],
            ['name' => 'Pekerja pabrik kimia', 'risk_score' => 2],
            ['name' => 'Pegawal/body guard', 'risk_score' => 2],
            ['name' => 'Nahkoda/kapten kapal', 'risk_score' => 2],

            // RISK SCORE 3 - High Risk (Direct Danger, Combat, Heights, Heavy Machinery)
            ['name' => 'Buruh pelabuhan', 'risk_score' => 3],
            ['name' => 'Penagih hutang (debt collctor)', 'risk_score' => 3],
            ['name' => 'Penjaga jalur kereta api', 'risk_score' => 3],
            ['name' => 'Pilot helikopter', 'risk_score' => 3],
            ['name' => 'Pekerja pada penggilingan beras/jagung/tepung', 'risk_score' => 3],
            ['name' => 'pilot/penerbang militer', 'risk_score' => 3],
            ['name' => 'Pilot penerbangan komersial', 'risk_score' => 3],
            ['name' => 'Pilot, trainer', 'risk_score' => 3],
            ['name' => 'Penebang dan pemrosesan kayu', 'risk_score' => 3],
            ['name' => 'Petugas penjaga penjara/sipir', 'risk_score' => 3],
            ['name' => 'Pekerja peleburan besi', 'risk_score' => 3],
            ['name' => 'Engineer pertambangan', 'risk_score' => 3],
            ['name' => 'Pekerja tambang lepas pantai', 'risk_score' => 3],
            ['name' => 'Penyelam profesional', 'risk_score' => 3],
            ['name' => 'Petugas otopsi jenasah', 'risk_score' => 3],
            ['name' => 'kelasi/anak buah kapal (ABK)', 'risk_score' => 3],
            ['name' => 'Pekerja tambang, dibawah tanah', 'risk_score' => 3],
            ['name' => 'Pekerja tambang, tidak dibawah tanah', 'risk_score' => 3],
            ['name' => 'Atlit profesional olahraga beresiko tinggi, termasuk bela diri, tinju, binaragawan', 'risk_score' => 3],
            ['name' => 'Pemeran pengganti (stuntman/stuntwoman)', 'risk_score' => 3],
            ['name' => 'Pemain sirkus/akrobat, di ketinggian', 'risk_score' => 3],
            ['name' => 'TNI AL', 'risk_score' => 3],
            ['name' => 'TNI AU', 'risk_score' => 3],
            ['name' => 'Pejabat Eselon I pada Lingkungan Kepolisian', 'risk_score' => 3],
            ['name' => 'Pejabat Eselon I pada Lingkungan Militer', 'risk_score' => 3],
            ['name' => 'TNI AD/ABRI', 'risk_score' => 3],
            ['name' => 'Pembalap profesional', 'risk_score' => 3],
            ['name' => 'Penebang pohon', 'risk_score' => 3],
            ['name' => 'Pekerja pabrik kayu', 'risk_score' => 3],
            ['name' => 'Petugas keamanan penjara (sipir)', 'risk_score' => 3],
            ['name' => 'Polisi pasukan khusus', 'risk_score' => 3],
            ['name' => 'Polisi cagar alam', 'risk_score' => 3],
            ['name' => 'Polisi penjaga jalur kereta api', 'risk_score' => 3],
            ['name' => 'Polisi perkebunan', 'risk_score' => 3],
            ['name' => 'Polisi hutan', 'risk_score' => 3],
            ['name' => 'Polisi anti teroris', 'risk_score' => 3],
            ['name' => 'Polisi penjaga perbatasan', 'risk_score' => 3],
            ['name' => 'Polisi penjinak bom', 'risk_score' => 3],
            ['name' => 'Pilot penerbangan non komersial', 'risk_score' => 3],
            ['name' => 'Pilot & awak kabin penerbangan komersial', 'risk_score' => 3],
            ['name' => 'Artileri', 'risk_score' => 3],
            ['name' => 'Operator alat berat (industri)', 'risk_score' => 3],
            ['name' => 'Operator mesin pengangkat barang/forklift', 'risk_score' => 3],
            ['name' => 'Petugas penjaga palang kereta api', 'risk_score' => 3],
            ['name' => 'Petugas pengaman perbatasan', 'risk_score' => 3],
            ['name' => 'Petugas penanganan pesenjataan', 'risk_score' => 3],
            ['name' => 'Pasukan khusus', 'risk_score' => 3],
            ['name' => 'Penerjun payung', 'risk_score' => 3],
            ['name' => 'Angkatan laut, penyelam dengan bahan peledak', 'risk_score' => 3],
            ['name' => 'Angkatan laut, penyelam tanpa bahan peledak', 'risk_score' => 3],
            ['name' => 'Penjinak bom', 'risk_score' => 3],
            ['name' => 'Masinis', 'risk_score' => 3],
            ['name' => 'Petugas pembasmi hama, dengan bahan kimia', 'risk_score' => 3],
            ['name' => 'Petugas pemasangan dan reparasi lift', 'risk_score' => 3],
            ['name' => 'Sopir kendaraan berlapis baja', 'risk_score' => 3],
            ['name' => 'Awak kabin pesawat militer', 'risk_score' => 3],
            ['name' => 'Petugas kebersihan gedung di ketinggian', 'risk_score' => 3],
            ['name' => 'Pekerja pembuatan asbes', 'risk_score' => 3],
            ['name' => 'Aerial Erector (pemasang kabel di ketinggian)', 'risk_score' => 3],
            ['name' => 'Petugas pemadam kebakaran (termasuk sukarelawan)', 'risk_score' => 3],
        ];

        foreach ($occupations as $occupation) {
            DB::table('occupations')->insert(array_merge($occupation, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
